name: Copy dbt Files to GCS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy dbt Files to GCS  
        run: |
          gsutil -m cp -r ./dbt_project/ gs://cicdtestteraform/dags
        env:
          GCS_KEY: ${{secrets.GCS_KEY}}
